const $=s=>document.querySelector(s);
async function me(){const r=await fetch("/api/auth/me");if(r.ok){const j=await r.json();showDash(j.user)}}
function showDash(user){$("#loginView").classList.add("hidden");$("#dashView").classList.remove("hidden");$("#who").textContent=user.email;loadAll();}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const j=await r.json();if(r.ok)showDash(j.user);else $("#loginMsg").textContent=j.error||"Login failed";});
$("#logout").onclick=async()=>{await fetch("/api/auth/logout",{method:"POST"});location.reload()};
async function loadAll(){await Promise.all([loadStats(),loadContacts(),loadServices()])}
async function loadStats(){const r=await fetch("/api/admin/stats");if(!r.ok)return location.reload();const x=await r.json();$("#statContacts").textContent=x.contacts;$("#statNew").textContent=x.newContacts;$("#statProgress").textContent=x.inProgress}
async function loadContacts(){const r=await fetch("/api/admin/contacts");if(!r.ok)return;const rows=await r.json();$("#contactsTable").innerHTML=rows.length?rows.map(c=>`<tr><td><b>${esc(c.name)}</b><small>${esc(c.email)}${c.phone?" · "+esc(c.phone):""}</small></td><td>${esc(c.service||"—")}</td><td><select onchange="updateContact(${c.id},this.value)">${["New","Contacted","In Progress","Resolved","Archived"].map(s=>`<option ${s===c.status?"selected":""}>${s}</option>`).join("")}</select></td><td>${new Date(c.created_at.replace(" ","T")+"Z").toLocaleString()}</td><td><a class="mini-wa" target="_blank" href="https://wa.me/${digits(c.phone)||"916306927241"}?text=${encodeURIComponent("Hello "+c.name+", this is CyberForce regarding your security inquiry.")}">WhatsApp ↗</a> <button class="mini-delete" onclick="deleteContact(${c.id})">Delete</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty">No contact requests yet.</td></tr>`}
async function updateContact(id,status){await fetch("/api/admin/contacts/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});loadStats()}
async function deleteContact(id){if(!confirm("Archive/delete this contact request?"))return;await fetch("/api/admin/contacts/"+id,{method:"DELETE"});loadAll()}
async function loadServices(){const r=await fetch("/api/admin/services");if(!r.ok)return;const rows=await r.json();$("#adminServices").innerHTML=rows.map(s=>`<div class="admin-service"><div><b>${esc(s.name)}</b><small>${esc(s.description)}</small></div><span>${s.status}</span><div><button onclick="editService(${s.id})">Edit</button><button onclick="deleteService(${s.id})">Delete</button></div></div>`).join("")}
async function addService(){const name=prompt("Service name?");if(!name)return;const description=prompt("Short description?")||"";await fetch("/api/admin/services",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description})});loadServices()}
async function editService(id){const r=await fetch("/api/admin/services");const all=await r.json();const s=all.find(x=>x.id===id);if(!s)return;const name=prompt("Service name",s.name);if(name===null)return;const description=prompt("Description",s.description);if(description===null)return;await fetch("/api/admin/services/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description})});loadServices()}
async function deleteService(id){if(!confirm("Delete service?"))return;await fetch("/api/admin/services/"+id,{method:"DELETE"});loadServices()}
function digits(v){return String(v||"").replace(/\D/g,"")||"916306927241"}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
me();
